version: '3'

services:

  php-fpm:
    container_name: lsp_php-fpm
    image: lsp/php-fpm
    build:
      context: .
    entrypoint:
      - php
      - -v

  php-fpm-local:
    container_name: lsp_php-fpm-local
    image: lsp/php-fpm-local
    build:
      dockerfile: local.Dockerfile
      context: .
    volumes:
      - ./:/var/www:cached
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    network_mode: bridge
    depends_on:
      - php-fpm
      - selenium-chrome
    links:
      - mysql
      - selenium-chrome

  nginx:
    container_name: lsp_nginx
    image: nginx:1.15
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./storage/logs/nginx/:/var/log/nginx:cached
    network_mode: bridge
    ports:
      - 80:80
    links:
      - php-fpm-local

  mysql:
    container_name: lsp_mysql
    image: mysql:5.6
    volumes:
      - ./storage/database/:/var/lib/mysql:cached
    environment:
      - "MYSQL_DATABASE=lsp"
      - "MYSQL_USER=lsp"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "TZ=UTC"
    network_mode: bridge
    ports:
      - 33060:3306

  selenium-chrome:
    container_name: lsp_selenium_chrome
    image: selenium/standalone-chrome:3.141.59-neon
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - JAVA_OPTS=-Xmx512m
      - SCREEN_WIDTH=1366
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
    privileged: true
    network_mode: bridge
